#! /usr/bin/env bash
set -euo pipefail

bad_usage() {
    echo "USAGE: ${0} COMMAND" >&2
    echo 'Available commands:' >&2
    echo '  dotfiles' >&2
    echo '  lite-de' >&2
    exit 1
}

if [[ ${#@} -eq 0 ]]; then
    bad_usage
fi

for arg in "${@}"; do
    case $arg in

        'dotfiles')
            start_pwd="$PWD"
            \cd "$(dirname "$0")"

            for dotfilename in bashrc emacs gitconfig screenrc vimrc zshrc tmux.conf; do
                srcname="$PWD/$dotfilename"
                dstname="$HOME/.$dotfilename"

                if [[ -f "$dstname" && ! -h "$dstname" ]]; then
                    echo "Move $dstname -> $dstname.backup.$(date +%F)"
                    mv -- "$dstname" "$dstname.backup.$(date +%F)"
                fi

                echo "Symlink $srcname -> $dstname"
                ln -sf -- "$srcname" "$dstname"
            done

            if [[ ! -e $HOME/.bash_profile ]]; then
                echo "source .bashrc" > "$HOME/.bash_profile"
            fi

            # Neovim
            mkdir -p "$HOME/.config/nvim"
            ln -sf "$PWD/nvimrc" "$HOME/.config/nvim/init.vim"

            \cd "$start_pwd"
            ;;

        'lite-de')
            start_pwd="$PWD"
            \cd "$(dirname "$0")/lite-de"

            ./install-debian-essentials
            ./install-x11-base
            ./install-x11-openbox
            ./install-x11-dwm
            ./install-x11-essentials
            cp xinitrc "$HOME/.xinitrc"
            mkdir "$HOME/bin"
            cp home-bin/* "$HOME/bin"

            \cd "$start_pwd"
            ;;

        '-h'|'-help'|'--help')
            bad_usage
            ;;

        *)
            echo "Unknown command: ${arg}" >&2
            exit 1
            ;;
    esac
done
