#! /bin/bash
set -e

start_pwd="$PWD"
\cd $(dirname $0)

if type git &>/dev/null; then
  git pull --ff-only
else
  echo "Could not update since git is not available" >&2
fi

for dotfilename in bashrc emacs gitconfig screenrc vimrc zshrc; do
  srcname="$PWD/$dotfilename"
  dstname="$HOME/.$dotfilename"

  if [[ -h "$dstname" ]]; then
    if [[ $(readlink $dstname) != $srcname ]]; then
      \ln -sfv -- "$srcname" "$dstname"
    fi

  elif [[ -e "$dstname" ]]; then
    \mv -v -- "$dstname" "$dstname.backup.$(date -I)"
    \ln -sv -- "$srcname" "$dstname"

  else
    \ln -sv -- "$srcname" "$dstname"
  fi
done

if [[ ! -e $HOME/.bash_profile ]]; then
  echo "source .bashrc" > $HOME/.bash_profile
fi

\cd $start_pwd

