#! /bin/bash

if [[ $PATH =~ "$HOME/bin" ]]; then
  export PATH=$HOME/bin:$PATH
fi

GIT=$(command -v git)
if [[ ! -z $GIT ]]; then
  $GIT stash save -q
  $GIT pull -q
  $GIT stash pop -q
else
  echo "Could not find/exec git!"
fi
