#! /usr/bin/env bash

# Dependencies
sudo apt install libx11-dev libxft-dev libxinerama-dev libwebkit2gtk-4.0-dev \
    libgcr-3-dev

# Sources
mkdir $HOME/src
cd $HOME/src

git clone https://github.com/lollek/dwm.git
cd dwm && make && sudo make install && cd ..

git clone https://github.com/lollek/dmenu.git
cd dmenu && make && sudo make install && cd ..

git clone https://github.com/lollek/st.git
cd st && make && sudo make install && cd ..

git clone https://github.com/lollek/surf.git
cd surf && make && sudo make install && cd ..
